from .bool import CheckboxWidget
from .choice import RadioWidget
from .choice import SelectWidget
from .date import DateWidget
from .date import DateTimeWidget
from .date import TimeWidget
from .file import FileWidget
from .number import NumberWidget
from .text import EMailWidget
from .text import HiddenWidget
from .text import PasswordWidget
from .text import SearchWidget
from .text import TextWidget
from .text import UrlWidget
